# Main font
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

opacity 0.8 

# Font size
font_size 14

# Fallback font for symbols (if needed)
symbol_map U+23FB-U+E0FF,U+E5FA-U+E5FF,U+E700-U+E7FF JetBrainsMono Nerd Font


# Adjust padding for a cleaner look
window_padding_width  5
window_padding_height 5

# Enable font ligatures (optional)
enable_ligatures yes

# Set the cursor shape and blinking
cursor_shape block
cursor_blink_interval 0.6

# Colorscheme (adjust as per your preference)
background #1e1e2e
foreground #c5cdd9
selection_background #414868
cursor #f38ba8

# Tabs and borders
active_tab_foreground #f38ba8
inactive_tab_foreground #c5cdd9
tab_background #1e1e2e
tab_bar_edge #414868

